#!/bin/sh
# require: sed, curl
UA="Mozilla/5.0 (Linux) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1 Chrome"
ENC="UTF-8"

SL=`echo $1|awk -F= '{print $1}'`
TL=`echo $1|awk -F= '{print $2}'`

curl -s https://translate.google.com/m \
 -d "hl=en" \
 -d "sl=$SL" \
 -d "tl=$TL" \
 -d "ie=$ENC" \
 -d "prev=_m" \
 --data-urlencode "q=$2" \
 -A "$UA" \
|sed 's/.*class="t0">\([^<]*\)<.*/\1\n/'
